"""Add goals and gamification fields

Revision ID: 0f7823c0011c
Revises: 17dd8e55baeb
Create Date: 2026-07-31 23:17:05.169671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f7823c0011c'
down_revision: Union[str, Sequence[str], None] = '17dd8e55baeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('goal_type', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='goaltype'), nullable=False),
    sa.Column('target_water_saved', sa.Float(), nullable=False),
    sa.Column('current_water_saved', sa.Float(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('achieved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user_profiles', sa.Column('current_streak', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('sustainability_badge', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'sustainability_badge')
    op.drop_column('user_profiles', 'current_streak')
    op.drop_table('user_goals')
    # ### end Alembic commands ###
